rem File ProDoor documentation
rem This batch file creates PRODOOR.MAN, which will contain the
rem complete documentation for prodoor.
echo off
type install.doc >prodoor.man
type prodoor.doc >>prodoor.man
type prohelp >>prodoor.man
type formfeed >>prodoor.man
type promail >>prodoor.man
type formfeed >>prodoor.man
type proentr >>prodoor.man
type formfeed >>prodoor.man
type provis >>prodoor.man
type formfeed >>prodoor.man
type read.me >>prodoor.man
type formfeed >>prodoor.man
type register.frm >>prodoor.man
type formfeed >>prodoor.man
