rem Print ProDoor documentation
rem We are about to make a 50 page print-out.
pause Prepare printer - press ^C to cancel.
type install.doc >prn
type prodoor.doc >>prn
type prohelp >>prn
type formfeed >>prn
type promail >>prn
type formfeed >>prn
type proentr >>prn
type formfeed >>prn
type provis >>prn
type formfeed >>prn
type read.me >>prn
type formfeed >>prn
type register.frm >>prn
type formfeed >>prn
