@echo off
cp -r -u dor\prodoor.exe dor\prolon.exe K:\
cp -r -u dor\prodoor.exe dor\prolon.exe M:\bin
cp -r -u dor\prodoor.exe dor\prolon.exe U:\dos
cp -r -u edt\proedit.exe dor\hstreset.exe M:\bin
cp -r -u dor\chkpath.exe dor\prosm.exe prons.com proecho.com L:\prod
cp -r -u kit\prokit.exe kit\proscrip.exe L:\pcb\door
cp -r -u prod.cnf provis proentr promail prohelp L:\prod
:cp -r -u prod.cnf provis proentr promail prohelp U:\prod
