rem translate all sample programs to c
:set tptc=-l -wj: -sc:\inc -i
tptc -3 types
tptc -3 acker
tptc -3 dia
tptc -3 dial
tptc -3 fmap
tptc -3 puzzle
tptc -3 qsort
tptc -3 sieve
tptc -3 test
tptc -3 test2
tptc -3 unsq
tptc -3 sortnode
tptc -3 varrec
tptc -3 smallrec
tptc -3 subrange
tptc -3 sets
tptc -3 pointers
tptc -3 linklist
tptc -3 findchrs
tptc -3 drawbox
tptc minicrt
tptc timedat4
tptc point4
tptc -m mtplus
dir \
