
(*
 * Copyright 1987, 1989 Samuel H. Smith;  All rights reserved
 *
 * This is a component of the ProDoor System.
 * Do not distribute modified versions without my permission.
 * Do not remove or alter this notice or any other copyright notice.
 * If you use this in your own program you must distribute source code.
 * Do not use any of this in a commercial product.
 *
 *)

(*
 * PCB ProDOOR - sysop/system functions (7-1-89)
 *
 *)

{$i prodef.inc}
{$i proovr.inc}

unit ProSysF;

interface

   Uses
     Dos,
     Tools,
     MdosIO,
     OpenShare,
     ProData,
     ProRoot;

{$i proclv.int}
{$i prorem.int}
{$i prowrit.int}
{$I proprof.int}
{$I proxlat.int}


implementation

{$i proclv.inc}
{$i prorem.inc}
{$i prowrit.inc}
{$I proprof.inc}     (* view user profile *)
{$I proxlat.inc}

end.


