
/*
 * Generated by TPTC - Translate Pascal to C
 *     Version 1.7g 05-02-88   (C) 1988 S.H.Smith
 */

#include <tptcsys.UNH>

/* 
 * Extra identifiers needed when translating tpas3.0 sources
 *
 * Add the line "uses tp3;" to Turbo Pascal 3.0 programs to gain
 * access to these definitions.
 *
 * (C) 1988 Samuel H. Smith
 *
 */ 

/* Unit tp3 */ 



   
#define IN_TP3  /* globals defined here */
#include <TP3.UNH>


   
boolean      keypressed(void)
   { 
     return kbhit();
   } 



void tp3_init()
{
   static char unit_initialized = 0;
   if (unit_initialized) return;

   unit_initialized = 1;


   assign(&lst,"prn"); 
   rewrite(&lst); 

   assign(&con,"con"); 
   rewrite(&con); 

   assign(&kbd,"con"); 
   reset(&kbd); 
}



