
/*
 * COPYRIGHT 1992 SAMUEL H. SMITH
 * ALL RIGHTS RESERVED
 *
 * THIS DOCUMENT CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS
 * PROPRIETARY TO SAMUEL H. SMITH DBA THE TOOL SHOP.
 *
 */

/* HDK.H - HS/LINK DEVELOPER KIT - PUBLIC DECLARATIONS */

/* these define services provided by the HDK library */
#include <hdktypes.h>
#include <hsopt.h>
#include <hslink.h>
#include <hstop.h>
#include <hstrans.h>
#include <hsrecv.h>

/* these define services provided by the application */
#include <hsdisp.h>
#include <hscomm.h>
#include <hsuid.h>
#include <hsmem.h>
#include <hsclock.h>

