
/*
 * COPYRIGHT 1992 SAMUEL H. SMITH
 * ALL RIGHTS RESERVED
 *
 * THIS DOCUMENT CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS
 * PROPRIETARY TO SAMUEL H. SMITH DBA THE TOOL SHOP.
 *
 */


/*********************************************************************
   * USER REGISTRATION AND TAMPER DETECTION PROVIDED BY APPLICATION *
 *********************************************************************/

int pascal blocked_userid(user_number *uid);

user_number pascal local_userid(void);

